### ISSUE TITLE
Moving domain objects to domain

### ISSUE THREAD

**Issue by ekinnalcaci** [CankayaUniversity/ceng-407-408-2023-2024-Insightio#10]
Our domain objects are Zone, Point, CameraType, ZoneType, CameraStatus. Please create separate files for them and move it to domain folder. Also, enums should be uppercase by convention. Please fix them for CameraType, ZoneType and CameraStatus.

**Comment by revtheundead** [comment]
Implemented with commit c6a8f7ff0968bdf5e396b045b14cb1794f4821f5
