### ISSUE TITLE
Implementing Count Report API

### ISSUE THREAD

**Issue by revtheundead** [CankayaUniversity/ceng-407-408-2023-2024-Insightio#7]
Count reports need to be kept in the database and queried when needed.

**Comment by ekinnalcaci** [comment]
added add operations for count reports

**Comment by ekinnalcaci** [comment]
finished with [commit](https://github.com/CankayaUniversity/ceng-407-408-2023-2024-Insightio/commit/f8b6851c48977d1a9db722012eeecf2b0c962f20)
