### ISSUE TITLE
Using DDD design Pattern + hexagonal architecture in BE

### ISSUE THREAD

**Issue by ekinnalcaci** [CankayaUniversity/ceng-407-408-2023-2024-Insightio#9]
Domain Driven Design has many benefits and widely used because of its usage of ubiquitous language, clear separation of concerns, single responsibility principle. We can apply this design pattern into our code. We must introduce our domain objects, our application layer (our service implementatiosn) and our infra layer for external operations not related with our domain (db operations, http clients, swagger configs). We should modify our code to apply hexagonal architecture design

**Comment by edanuraltnk** [comment]
Necessary arrangements were made. commit dbc1c51
